import { Category, Type } from "@/types/move";

export type TM = {
  number: string;
  name: string;
  type: Type;
  power: number | null;
  accuracy: number | string | null;
  pp: number;
  locations: string[];
  category?: Category; // category is now optional
};

export const gen1Tms: TM[] = [
  {
    number: "01",
    name: "Mega Punch",
    type: "NORMAL",
    power: 80,
    accuracy: 85,
    pp: 20,
    locations: ["Mt. Moon", "Celadon City (Department Store - $3,000)"],
  },
  {
    number: "02",
    name: "Razor Wind",
    type: "NORMAL",
    power: 80,
    accuracy: 100,
    pp: 10,
    locations: [
      "Rocket Hideout (B4F)",
      "Celadon City (Department Store - $2,000)",
    ],
  },
  {
    number: "03",
    name: "Swords Dance",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 20,
    locations: ["Silph Co."],
  },
  {
    number: "04",
    name: "Whirlwind",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 20,
    locations: ["Route 4"],
  },
  {
    number: "05",
    name: "Mega Kick",
    type: "NORMAL",
    power: 120,
    accuracy: 75,
    pp: 5,
    locations: ["Victory Road", "Celadon City (Department Store - $3,000)"],
  },
  {
    number: "06",
    name: "Toxic",
    type: "POISON",
    power: null,
    accuracy: 90,
    pp: 10,
    locations: ["Fuchsia City (Gym - defeat Koga)"],
  },
  {
    number: "07",
    name: "Horn Drill",
    type: "NORMAL",
    power: null,
    accuracy: 30,
    pp: 5,
    locations: [
      "Rocket Hideout (B2F)",
      "Celadon City (Department Store - $2,000)",
    ],
  },
  {
    number: "08",
    name: "Body Slam",
    type: "NORMAL",
    power: 85,
    accuracy: 100,
    pp: 15,
    locations: ["SS Anne"],
  },
  {
    number: "09",
    name: "Take Down",
    type: "NORMAL",
    power: 90,
    accuracy: 85,
    pp: 20,
    locations: ["Saffron City", "Celadon City (Department Store - $3,000)"],
  },
  {
    number: "10",
    name: "Double-Edge",
    type: "NORMAL",
    power: 120,
    accuracy: 100,
    pp: 15,
    locations: ["Rocket Hideout (B3F)"],
  },
  {
    number: "11",
    name: "Bubble Beam",
    type: "WATER",
    power: 65,
    accuracy: 100,
    pp: 20,
    locations: ["Cerulean City (Gym - defeat Misty)"],
  },
  {
    number: "12",
    name: "Water Gun",
    type: "WATER",
    power: 40,
    accuracy: 100,
    pp: 25,
    locations: ["Mt. Moon"],
  },
  {
    number: "13",
    name: "Ice Beam",
    type: "ICE",
    power: 90,
    accuracy: 100,
    pp: 10,
    locations: ["Celadon City (Department Store roof - give girl Fresh Water)"],
  },
  {
    number: "14",
    name: "Blizzard",
    type: "ICE",
    power: 110,
    accuracy: 70,
    pp: 5,
    locations: ["Pokémon Mansion"],
  },
  {
    number: "15",
    name: "Hyper Beam",
    type: "NORMAL",
    power: 150,
    accuracy: 90,
    pp: 5,
    locations: ["Celadon City (Game Corner - 5,500 Coins)"],
  },
  {
    number: "16",
    name: "Pay Day",
    type: "NORMAL",
    power: 40,
    accuracy: 100,
    pp: 20,
    locations: ["Route 12"],
  },
  {
    number: "17",
    name: "Submission",
    type: "FIGHTING",
    power: 80,
    accuracy: 80,
    pp: 20,
    locations: ["Victory Road", "Celadon City (Department Store - $3,000)"],
  },
  {
    number: "18",
    name: "Counter",
    type: "FIGHTING",
    power: null,
    accuracy: 100,
    pp: 20,
    locations: ["Celadon City (Department Store - 3F)"],
  },
  {
    number: "19",
    name: "Seismic Toss",
    type: "FIGHTING",
    power: null,
    accuracy: 100,
    pp: 20,
    locations: ["Route 25"],
  },
  {
    number: "20",
    name: "Rage",
    type: "NORMAL",
    power: 20,
    accuracy: 100,
    pp: 20,
    locations: ["Route 15"],
  },
  {
    number: "21",
    name: "Mega Drain",
    type: "GRASS",
    power: 40,
    accuracy: 100,
    pp: 15,
    locations: ["Celadon City (Gym - defeat Erika)"],
  },
  {
    number: "22",
    name: "Solar Beam",
    type: "GRASS",
    power: 120,
    accuracy: 100,
    pp: 10,
    locations: ["Pokémon Mansion"],
  },
  {
    number: "23",
    name: "Dragon Rage",
    type: "DRAGON",
    power: null,
    accuracy: 100,
    pp: 10,
    locations: ["Celadon City (Game Corner - 3,300 Coins)"],
  },
  {
    number: "24",
    name: "Thunderbolt",
    type: "ELECTRIC",
    power: 90,
    accuracy: 100,
    pp: 15,
    locations: ["Vermilion City (Gym - defeat Lt. Surge)"],
  },
  {
    number: "25",
    name: "Thunder",
    type: "ELECTRIC",
    power: 110,
    accuracy: 70,
    pp: 10,
    locations: ["Power Plant"],
  },
  {
    number: "26",
    name: "Earthquake",
    type: "GROUND",
    power: 100,
    accuracy: 100,
    pp: 10,
    locations: ["Silph Co."],
  },
  {
    number: "27",
    name: "Fissure",
    type: "GROUND",
    power: null,
    accuracy: 30,
    pp: 5,
    locations: ["Viridian City (Gym - defeat Giovanni)"],
  },
  {
    number: "28",
    name: "Dig",
    type: "GROUND",
    power: 80,
    accuracy: 100,
    pp: 10,
    locations: ["Cerulean City"],
  },
  {
    number: "29",
    name: "Psychic",
    type: "PSYCHIC",
    power: 90,
    accuracy: 100,
    pp: 10,
    locations: ["Saffron City"],
  },
  {
    number: "30",
    name: "Teleport",
    type: "PSYCHIC",
    power: null,
    accuracy: null,
    pp: 20,
    locations: ["Route 9"],
  },
  {
    number: "31",
    name: "Mimic",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["Saffron City"],
  },
  {
    number: "32",
    name: "Double Team",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 15,
    locations: ["Fuchsia City", "Celadon City (Department Store - $1,000)"],
  },
  {
    number: "33",
    name: "Reflect",
    type: "PSYCHIC",
    power: null,
    accuracy: null,
    pp: 20,
    locations: ["Power Plant", "Celadon City (Department Store - $1,000)"],
  },
  {
    number: "34",
    name: "Bide",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["Pewter City (Gym - defeat Brock)"],
  },
  {
    number: "35",
    name: "Metronome",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["Cinnabar Island (Pokémon Lab)"],
  },
  {
    number: "36",
    name: "Self-Destruct",
    type: "NORMAL",
    power: 200,
    accuracy: 100,
    pp: 5,
    locations: ["Silph Co."],
  },
  {
    number: "37",
    name: "Egg Bomb",
    type: "NORMAL",
    power: 100,
    accuracy: 75,
    pp: 10,
    locations: ["Fuchsia City", "Celadon City (Department Store - $2,000)"],
  },
  {
    number: "38",
    name: "Fire Blast",
    type: "FIRE",
    power: 110,
    accuracy: 85,
    pp: 5,
    locations: ["Cinnabar Island (Gym - defeat Blaine)"],
  },
  {
    number: "39",
    name: "Swift",
    type: "NORMAL",
    power: 60,
    accuracy: "∞",
    pp: 20,
    locations: ["Route 12 (Lookout Station)"],
  },
  {
    number: "40",
    name: "Skull Bash",
    type: "NORMAL",
    power: 130,
    accuracy: 100,
    pp: 10,
    locations: ["Safari Zone"],
  },
  {
    number: "41",
    name: "Soft-Boiled",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 5,
    locations: ["Celadon City"],
  },
  {
    number: "42",
    name: "Dream Eater",
    type: "PSYCHIC",
    power: 100,
    accuracy: 100,
    pp: 15,
    locations: ["Viridian City"],
  },
  {
    number: "43",
    name: "Sky Attack",
    type: "FLYING",
    power: 140,
    accuracy: 90,
    pp: 5,
    locations: ["Victory Road"],
  },
  {
    number: "44",
    name: "Rest",
    type: "PSYCHIC",
    power: null,
    accuracy: null,
    pp: 5,
    locations: ["SS Anne"],
  },
  {
    number: "45",
    name: "Thunder Wave",
    type: "ELECTRIC",
    power: null,
    accuracy: 90,
    pp: 20,
    locations: ["Route 24"],
  },
  {
    number: "46",
    name: "Psywave",
    type: "PSYCHIC",
    power: null,
    accuracy: 100,
    pp: 15,
    locations: ["Saffron City (Gym - defeat Sabrina)"],
  },
  {
    number: "47",
    name: "Explosion",
    type: "NORMAL",
    power: 250,
    accuracy: 100,
    pp: 5,
    locations: ["Victory Road"],
  },
  {
    number: "48",
    name: "Rock Slide",
    type: "ROCK",
    power: 75,
    accuracy: 90,
    pp: 10,
    locations: ["Celadon City (Department Store roof - give girl Soda Pop)"],
  },
  {
    number: "49",
    name: "Tri Attack",
    type: "NORMAL",
    power: 80,
    accuracy: 100,
    pp: 10,
    locations: ["Celadon City (Department Store roof - give girl Lemonade)"],
  },
  {
    number: "50",
    name: "Substitute",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["Celadon City (Game Corner - 7,700 Coins)"],
  },
];

export const gen2Tms: TM[] = [
  {
    number: "01",
    name: "Dynamic Punch",
    type: "FIGHTING",
    power: 100,
    accuracy: 50,
    pp: 5,
    locations: ["Cianwood City (Gym - defeat Chuck)"],
  },
  {
    number: "02",
    name: "Headbutt",
    type: "NORMAL",
    power: 70,
    accuracy: 100,
    pp: 15,
    locations: ["Ilex Forest", "Goldenrod City (Department Store - $2,000)"],
  },
  {
    number: "03",
    name: "Curse",
    type: "GHOST",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["Celadon City (Celadon Mansion, at night)"],
  },
  {
    number: "04",
    name: "Rollout",
    type: "ROCK",
    power: 30,
    accuracy: 90,
    pp: 20,
    locations: ["Route 35"],
  },
  {
    number: "05",
    name: "Roar",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 20,
    locations: ["Route 32"],
  },
  {
    number: "06",
    name: "Toxic",
    type: "POISON",
    power: null,
    accuracy: 90,
    pp: 10,
    locations: ["Fuchsia City (Gym - defeat Janine)"],
  },
  {
    number: "07",
    name: "Zap Cannon",
    type: "ELECTRIC",
    power: 120,
    accuracy: 50,
    pp: 5,
    locations: ["Power Plant"],
  },
  {
    number: "08",
    name: "Rock Smash",
    type: "FIGHTING",
    power: 40,
    accuracy: 100,
    pp: 15,
    locations: ["Route 36", "Goldenrod City (Department Store - $2,000)"],
  },
  {
    number: "09",
    name: "Psych Up",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["(Trade Abra/Kadabra from Generation 1)"],
  },
  {
    number: "10",
    name: "Hidden Power",
    type: "NORMAL",
    power: 60,
    accuracy: 100,
    pp: 15,
    locations: ["Lake of Rage", "Celadon City (Department Store - $3,000)"],
  },
  {
    number: "11",
    name: "Sunny Day",
    type: "FIRE",
    power: null,
    accuracy: null,
    pp: 5,
    locations: [
      "Celadon City (Department Store - $2,000)",
      "Goldenrod Radio Tower (3F - from woman after defeating Team Rocket)",
    ],
  },
  {
    number: "12",
    name: "Sweet Scent",
    type: "NORMAL",
    power: null,
    accuracy: 100,
    pp: 20,
    locations: ["Route 34"],
  },
  {
    number: "13",
    name: "Snore",
    type: "NORMAL",
    power: 50,
    accuracy: 100,
    pp: 15,
    locations: ["Route 39"],
  },
  {
    number: "14",
    name: "Blizzard",
    type: "ICE",
    power: 110,
    accuracy: 70,
    pp: 5,
    locations: ["Goldenrod City (Game Corner - 5,500 Coins)"],
  },
  {
    number: "15",
    name: "Hyper Beam",
    type: "NORMAL",
    power: 150,
    accuracy: 90,
    pp: 5,
    locations: ["Celadon City (Game Corner - 7,500 Coins)"],
  },
  {
    number: "16",
    name: "Icy Wind",
    type: "ICE",
    power: 55,
    accuracy: 95,
    pp: 15,
    locations: ["Mahogany Town (Gym - defeat Pryce)"],
  },
  {
    number: "17",
    name: "Protect",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["Celadon City (Department Store - $3,000)"],
  },
  {
    number: "18",
    name: "Rain Dance",
    type: "WATER",
    power: null,
    accuracy: null,
    pp: 5,
    locations: ["Slowpoke Well"],
  },
  {
    number: "19",
    name: "Giga Drain",
    type: "GRASS",
    power: 75,
    accuracy: 100,
    pp: 10,
    locations: ["Celadon City (Gym - defeat Erika)"],
  },
  {
    number: "20",
    name: "Endure",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["Burned Tower"],
  },
  {
    number: "21",
    name: "Frustration",
    type: "NORMAL",
    power: null,
    accuracy: 100,
    pp: 20,
    locations: [
      "Goldenrod City (Department Store 5F on Sunday, show woman unhappy Pokémon)",
    ],
  },
  {
    number: "22",
    name: "Solar Beam",
    type: "GRASS",
    power: 120,
    accuracy: 100,
    pp: 10,
    locations: ["Route 27"],
  },
  {
    number: "23",
    name: "Iron Tail",
    type: "STEEL",
    power: 100,
    accuracy: 75,
    pp: 15,
    locations: ["Olivine City (Gym - defeat Jasmine)"],
  },
  {
    number: "24",
    name: "Dragon Breath",
    type: "DRAGON",
    power: 60,
    accuracy: 100,
    pp: 20,
    locations: ["Blackthorn City (Gym - defeat Clair)"],
  },
  {
    number: "25",
    name: "Thunder",
    type: "ELECTRIC",
    power: 110,
    accuracy: 70,
    pp: 10,
    locations: ["Goldenrod City (Game Corner - 5,500 Coins)"],
  },
  {
    number: "26",
    name: "Earthquake",
    type: "GROUND",
    power: 100,
    accuracy: 100,
    pp: 10,
    locations: ["Victory Road"],
  },
  {
    number: "27",
    name: "Return",
    type: "NORMAL",
    power: null,
    accuracy: 100,
    pp: 20,
    locations: [
      "Goldenrod City (Department Store 5F on Sunday, show woman happy Pokémon)",
    ],
  },
  {
    number: "28",
    name: "Dig",
    type: "GROUND",
    power: 80,
    accuracy: 100,
    pp: 10,
    locations: ["National Park"],
  },
  {
    number: "29",
    name: "Psychic",
    type: "PSYCHIC",
    power: 90,
    accuracy: 100,
    pp: 10,
    locations: ["Saffron City", "Celadon City (Department Store - $3,000)"],
  },
  {
    number: "30",
    name: "Shadow Ball",
    type: "GHOST",
    power: 80,
    accuracy: 100,
    pp: 15,
    locations: ["Ecruteak City (Gym - defeat Morty)"],
  },
  {
    number: "31",
    name: "Mud-Slap",
    type: "GROUND",
    power: 20,
    accuracy: 100,
    pp: 10,
    locations: ["Violet City (Gym - defeat Falkner)"],
  },
  {
    number: "32",
    name: "Double Team",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 15,
    locations: ["Celadon City (Game Corner - 1,500 Coins)"],
  },
  {
    number: "33",
    name: "Ice Punch",
    type: "ICE",
    power: 75,
    accuracy: 100,
    pp: 15,
    locations: ["Goldenrod City (Department Store - $3,000)"],
  },
  {
    number: "34",
    name: "Swagger",
    type: "NORMAL",
    power: null,
    accuracy: 85,
    pp: 15,
    locations: ["Olivine City (Lighthouse)"],
  },
  {
    number: "35",
    name: "Sleep Talk",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["Goldenrod City (Department Store basement)"],
  },
  {
    number: "36",
    name: "Sludge Bomb",
    type: "POISON",
    power: 90,
    accuracy: 100,
    pp: 10,
    locations: ["Route 43"],
  },
  {
    number: "37",
    name: "Sandstorm",
    type: "ROCK",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["Route 27"],
  },
  {
    number: "38",
    name: "Fire Blast",
    type: "FIRE",
    power: 110,
    accuracy: 85,
    pp: 5,
    locations: ["Goldenrod City (Game Corner - 5,500 Coins)"],
  },
  {
    number: "39",
    name: "Swift",
    type: "NORMAL",
    power: 60,
    accuracy: "∞",
    pp: 20,
    locations: ["Union Cave (B1F northwest)"],
  },
  {
    number: "40",
    name: "Defense Curl",
    type: "NORMAL",
    power: null,
    accuracy: null,
    pp: 40,
    locations: ["Mt. Mortar"],
  },
  {
    number: "41",
    name: "Thunder Punch",
    type: "ELECTRIC",
    power: 75,
    accuracy: 100,
    pp: 15,
    locations: ["Goldenrod City (Department Store - $3,000)"],
  },
  {
    number: "42",
    name: "Dream Eater",
    type: "PSYCHIC",
    power: 100,
    accuracy: 100,
    pp: 15,
    locations: ["Viridian City"],
  },
  {
    number: "43",
    name: "Detect",
    type: "FIGHTING",
    power: null,
    accuracy: null,
    pp: 5,
    locations: ["Lake of Rage"],
  },
  {
    number: "44",
    name: "Rest",
    type: "PSYCHIC",
    power: null,
    accuracy: null,
    pp: 5,
    locations: ["Ice Path"],
  },
  {
    number: "45",
    name: "Attract",
    type: "NORMAL",
    power: null,
    accuracy: 100,
    pp: 15,
    locations: ["Goldenrod City (Gym - defeat Whitney and her damn Miltank)"],
  },
  {
    number: "46",
    name: "Thief",
    type: "DARK",
    power: 60,
    accuracy: 100,
    pp: 25,
    locations: ["Team Rocket HQ"],
  },
  {
    number: "47",
    name: "Steel Wing",
    type: "STEEL",
    power: 70,
    accuracy: 90,
    pp: 25,
    locations: ["Route 28"],
  },
  {
    number: "48",
    name: "Fire Punch",
    type: "FIRE",
    power: 75,
    accuracy: 100,
    pp: 15,
    locations: ["Goldenrod City (Department Store - $3,000)"],
  },
  {
    number: "49",
    name: "Fury Cutter",
    type: "BUG",
    power: 40,
    accuracy: 95,
    pp: 20,
    locations: ["Azalea Town (Gym - defeat Bugsy)"],
  },
  {
    number: "50",
    name: "Nightmare",
    type: "GHOST",
    power: null,
    accuracy: 100,
    pp: 15,
    locations: ["Route 31 (deliver Randy's mail)"],
  },
];

export const gen3TMs: TM[] = [
  {
    number: "01",
    name: "Focus Punch",
    type: "FIGHTING",
    category: "Physical",
    power: 150,
    accuracy: 100,
    pp: 20,
    locations: [
      "Route 115 (south)(Pickup ability in Emerald, 1% chance at level 71-90)",
    ],
  },
  {
    number: "02",
    name: "Dragon Claw",
    type: "DRAGON",
    category: "Physical",
    power: 80,
    accuracy: 100,
    pp: 15,
    locations: ["Meteor Falls"],
  },
  {
    number: "03",
    name: "Water Pulse",
    type: "WATER",
    category: "Special",
    power: 60,
    accuracy: 100,
    pp: 20,
    locations: ["Sootopolis City (Gym - defeat Wallace/Juan)"],
  },
  {
    number: "04",
    name: "Calm Mind",
    type: "PSYCHIC",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 20,
    locations: ["Mossdeep City (Gym - defeat Tate & Liza)"],
  },
  {
    number: "05",
    name: "Roar",
    type: "NORMAL",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 20,
    locations: ["Route 114"],
  },
  {
    number: "06",
    name: "Toxic",
    type: "POISON",
    category: "Status",
    power: null,
    accuracy: 90,
    pp: 10,
    locations: ["Fiery Path (west; requires Strength)"],
  },
  {
    number: "07",
    name: "Hail",
    type: "ICE",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["Shoal Cave"],
  },
  {
    number: "08",
    name: "Bulk Up",
    type: "FIGHTING",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 20,
    locations: ["Dewford Town (Gym - defeat Brawly)"],
  },
  {
    number: "09",
    name: "Bullet Seed",
    type: "GRASS",
    category: "Physical",
    power: 25,
    accuracy: 100,
    pp: 30,
    locations: ["Route 104"],
  },
  {
    number: "10",
    name: "Hidden power",
    type: "NORMAL",
    category: "Special",
    power: 60,
    accuracy: 100,
    pp: 15,
    locations: [
      "Fortree City (north; answer questions Right, Right, Left)",
      "Slateport City (Slateport Market - $3,000)",
    ],
  },
  {
    number: "11",
    name: "Sunny Day",
    type: "FIRE",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 5,
    locations: [
      "Scorched Slab (south; requires Surf)",
      "Trainer Hill (defeat trainers in under 12 minutes)",
    ],
  },
  {
    number: "12",
    name: "Taunt",
    type: "DARK",
    category: "Status",
    power: null,
    accuracy: 100,
    pp: 20,
    locations: ["Route 110 (Trick House, prize after 5th puzzle)"],
  },
  {
    number: "13",
    name: "Ice Beam",
    type: "ICE",
    category: "Special",
    power: 90,
    accuracy: 100,
    pp: 10,
    locations: [
      "Abandoned Ship (Storage Room, requires Dive/Surf)",
      "Mauville City (Game Corner - 4,000 Coins)",
    ],
  },
  {
    number: "14",
    name: "Blizzard",
    type: "ICE",
    category: "Special",
    power: 110,
    accuracy: 70,
    pp: 5,
    locations: ["Lilycove City (Lilycove Department Store - $5,500)"],
  },
  {
    number: "15",
    name: "Hyper Beam",
    type: "NORMAL",
    category: "Special",
    power: 150,
    accuracy: 90,
    pp: 5,
    locations: ["Lilycove City (Lilycove Department Store - $7,500)"],
  },
  {
    number: "16",
    name: "Light Screen",
    type: "PSYCHIC",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 30,
    locations: ["Lilycove City (Lilycove Department Store - $3,000)"],
  },
  {
    number: "17",
    name: "Protect",
    type: "NORMAL",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["Lilycove City (Lilycove Department Store - $3,000)"],
  },
  {
    number: "18",
    name: "Rain Dance",
    type: "WATER",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 5,
    locations: ["Abandoned Ship (B1F)"],
  },
  {
    number: "19",
    name: "Giga Drain",
    type: "GRASS",
    category: "Special",
    power: 75,
    accuracy: 100,
    pp: 10,
    locations: [
      "Route 123",
      "Trainer Hill (defeat trainers in under 12 minutes)",
    ],
  },
  {
    number: "20",
    name: "Safeguard",
    type: "NORMAL",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 25,
    locations: ["Lilycove City (Lilycove Department Store - $3,000)"],
  },
  {
    number: "21",
    name: "Frustration",
    type: "NORMAL",
    category: "Physical",
    power: null,
    accuracy: 100,
    pp: 20,
    locations: [
      "Pacifidlog Town (south; received if Pokémon's friendship low)",
    ],
  },
  {
    number: "22",
    name: "Solar Beam",
    type: "GRASS",
    category: "Special",
    power: 120,
    accuracy: 100,
    pp: 10,
    locations: ["Safari Zone"],
  },
  {
    number: "23",
    name: "Iron Tail",
    type: "STEEL",
    category: "Physical",
    power: 100,
    accuracy: 75,
    pp: 15,
    locations: ["Meteor Falls"],
  },
  {
    number: "24",
    name: "Thunderbolt",
    type: "ELECTRIC",
    category: "Special",
    power: 90,
    accuracy: 100,
    pp: 15,
    locations: [
      "Mauville City (from Wattson after shutting down generator)",
      "Mauville City (Mauville Game Corner - 4,000 Coins)",
    ],
  },
  {
    number: "25",
    name: "Thunder",
    type: "ELECTRIC",
    category: "Special",
    power: 110,
    accuracy: 70,
    pp: 10,
    locations: ["Lilycove City (Lilycove Department Store - $5,500)"],
  },
  {
    number: "26",
    name: "Earthquake",
    type: "GROUND",
    category: "Physical",
    power: 100,
    accuracy: 100,
    pp: 10,
    locations: [
      "Seafloor Cavern (final room with Groudon/Kyogre)",
      "(Pickup ability in Emerald, 1% chance at level 91-100)",
    ],
  },
  {
    number: "27",
    name: "Return",
    type: "NORMAL",
    category: "Physical",
    power: null,
    accuracy: 100,
    pp: 20,
    locations: [
      "Pacifidlog Town (south; received if Pokémon's friendship high)",
      "Fallarbor Town (south; trade Meteorite)",
    ],
  },
  {
    number: "28",
    name: "Dig",
    type: "GROUND",
    category: "Physical",
    power: 80,
    accuracy: 100,
    pp: 10,
    locations: ["Route 114"],
  },
  {
    number: "29",
    name: "Psychic",
    type: "PSYCHIC",
    category: "Special",
    power: 90,
    accuracy: 100,
    pp: 10,
    locations: [
      "Victory Road (B1F, northeast)",
      "Mauville City (Game Corner - 3,500 Coins)",
    ],
  },
  {
    number: "30",
    name: "Shadow Ball",
    type: "GHOST",
    category: "Special",
    power: 80,
    accuracy: 100,
    pp: 15,
    locations: ["Mt. Pyre (6F)"],
  },
  {
    number: "31",
    name: "Brick Break",
    type: "FIGHTING",
    category: "Physical",
    power: 75,
    accuracy: 100,
    pp: 15,
    locations: [
      "Sootopolis City (northwest)",
      "Trainer Hill (defeat trainers in under 12 minutes)",
    ],
  },
  {
    number: "32",
    name: "Double Team",
    type: "NORMAL",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 15,
    locations: ["Mauville City (Mauville Game Corner - 1,500 Coins)"],
  },
  {
    number: "33",
    name: "Reflect",
    type: "PSYCHIC",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 20,
    locations: ["Lilycove City (Lilycove Department Store - $3,000)"],
  },
  {
    number: "34",
    name: "Shock Wave",
    type: "ELECTRIC",
    category: "Special",
    power: 60,
    accuracy: null,
    pp: 20,
    locations: ["Mauville City (Gym - defeat Wattson)"],
  },
  {
    number: "35",
    name: "Flamethrower",
    type: "FIRE",
    category: "Special",
    power: 90,
    accuracy: 100,
    pp: 15,
    locations: ["Mauville City (Mauville Game Corner - 4,000 Coins)"],
  },
  {
    number: "36",
    name: "Sludge Bomb",
    type: "POISON",
    category: "Special",
    power: 90,
    accuracy: 100,
    pp: 10,
    locations: ["Dewford Town"],
  },
  {
    number: "37",
    name: "Sandstorm",
    type: "ROCK",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["Route 111 (south)"],
  },
  {
    number: "38",
    name: "Fire Blast",
    type: "FIRE",
    category: "Special",
    power: 110,
    accuracy: 85,
    pp: 5,
    locations: ["Lilycove City (Lilycove Department Store - $5,500)"],
  },
  {
    number: "39",
    name: "Rock Tomb",
    type: "ROCK",
    category: "Physical",
    power: 60,
    accuracy: 95,
    pp: 15,
    locations: ["Rustboro City (Gym - defeat Roxanne)"],
  },
  {
    number: "40",
    name: "Aerial Ace",
    type: "FLYING",
    category: "Physical",
    power: 60,
    accuracy: null,
    pp: 20,
    locations: ["Fortree City (Gym - defeat Winona)"],
  },
  {
    number: "41",
    name: "Torment",
    type: "DARK",
    category: "Status",
    power: null,
    accuracy: 100,
    pp: 15,
    locations: ["Slateport City"],
  },
  {
    number: "42",
    name: "Facade",
    type: "NORMAL",
    category: "Physical",
    power: 70,
    accuracy: 100,
    pp: 20,
    locations: ["Petalburg City (Gym - defeat Norman)"],
  },
  {
    number: "43",
    name: "Secret power",
    type: "NORMAL",
    category: "Physical",
    power: 70,
    accuracy: 100,
    pp: 20,
    locations: [
      "Route 111 (north; from guy in front of tree)",
      "Slateport City (Slateport Market - $3,000)",
    ],
  },
  {
    number: "44",
    name: "Rest",
    type: "PSYCHIC",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 5,
    locations: [
      "Lilycove City (east; from man in house)",
      "(Pickup ability in Emerald, 1% chance at level 51-70)",
    ],
  },
  {
    number: "45",
    name: "Attract",
    type: "NORMAL",
    category: "Status",
    power: null,
    accuracy: 100,
    pp: 15,
    locations: ["Verdanturf Town"],
  },
  {
    number: "46",
    name: "Thief",
    type: "DARK",
    category: "Physical",
    power: 60,
    accuracy: 100,
    pp: 25,
    locations: ["Slateport City"],
  },
  {
    number: "47",
    name: "Steel Wing",
    type: "STEEL",
    category: "Physical",
    power: 70,
    accuracy: 90,
    pp: 25,
    locations: ["Granite Cave"],
  },
  {
    number: "48",
    name: "Skill Swap",
    type: "PSYCHIC",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["Mt. Pyre (outside 2F)"],
  },
  {
    number: "49",
    name: "Snatch",
    type: "DARK",
    category: "Status",
    power: null,
    accuracy: null,
    pp: 10,
    locations: ["SS Tidal"],
  },
  {
    number: "50",
    name: "Overheat",
    type: "FIRE",
    category: "Special",
    power: 130,
    accuracy: 90,
    pp: 5,
    locations: ["Lavaridge Town (Gym - defeat Flannery)"],
  },
];
