const RBY: string[] = [];

const GSC = [
  {
    key: "Berry Juice",
    text: "Berry Juice",
    value: "Berry Juice",
  },
  {
    key: "Berry",
    text: "Berry",
    value: "Berry",
  },
  {
    key: "Berserk Gene",
    text: "Berserk Gene",
    value: "Berserk Gene",
  },
  {
    key: "Bitter Berry",
    text: "Bitter Berry",
    value: "Bitter Berry",
  },
  {
    key: "Black Belt",
    text: "Black Belt",
    value: "Black Belt",
  },
  {
    key: "Black Glasses",
    text: "Black Glasses",
    value: "Black Glasses",
  },
  {
    key: "Bright Powder",
    text: "Bright Powder",
    value: "Bright Powder",
  },
  {
    key: "Burnt Berry",
    text: "Burnt Berry",
    value: "Burnt Berry",
  },
  {
    key: "Charcoal",
    text: "Charcoal",
    value: "Charcoal",
  },
  {
    key: "Dragon Fang",
    text: "Dragon Fang",
    value: "Dragon Fang",
  },
  {
    key: "Dragon Scale",
    text: "Dragon Scale",
    value: "Dragon Scale",
  },
  {
    key: "Fast Ball",
    text: "Fast Ball",
    value: "Fast Ball",
  },
  {
    key: "Fire Stone",
    text: "Fire Stone",
    value: "Fire Stone",
  },
  {
    key: "Focus Band",
    text: "Focus Band",
    value: "Focus Band",
  },
  {
    key: "Friend Ball",
    text: "Friend Ball",
    value: "Friend Ball",
  },
  {
    key: "Gold Berry",
    text: "Gold Berry",
    value: "Gold Berry",
  },
  {
    key: "Great Ball",
    text: "Great Ball",
    value: "Great Ball",
  },
  {
    key: "Hard Stone",
    text: "Hard Stone",
    value: "Hard Stone",
  },
  {
    key: "Heavy Ball",
    text: "Heavy Ball",
    value: "Heavy Ball",
  },
  {
    key: "Ice Berry",
    text: "Ice Berry",
    value: "Ice Berry",
  },
  {
    key: "King's Rock",
    text: "King's Rock",
    value: "King's Rock",
  },
  {
    key: "Leaf Stone",
    text: "Leaf Stone",
    value: "Leaf Stone",
  },
  {
    key: "Leftovers",
    text: "Leftovers",
    value: "Leftovers",
  },
  {
    key: "Level Ball",
    text: "Level Ball",
    value: "Level Ball",
  },
  {
    key: "Light Ball",
    text: "Light Ball",
    value: "Light Ball",
  },
  {
    key: "Love Ball",
    text: "Love Ball",
    value: "Love Ball",
  },
  {
    key: "Lucky Punch",
    text: "Lucky Punch",
    value: "Lucky Punch",
  },
  {
    key: "Lure Ball",
    text: "Lure Ball",
    value: "Lure Ball",
  },
  {
    key: "Magnet",
    text: "Magnet",
    value: "Magnet",
  },
  {
    key: "Mail",
    text: "Mail",
    value: "Mail",
  },
  {
    key: "Master Ball",
    text: "Master Ball",
    value: "Master Ball",
  },
  {
    key: "Metal Coat",
    text: "Metal Coat",
    value: "Metal Coat",
  },
  {
    key: "Metal Powder",
    text: "Metal Powder",
    value: "Metal Powder",
  },
  {
    key: "Mint Berry",
    text: "Mint Berry",
    value: "Mint Berry",
  },
  {
    key: "Miracle Berry",
    text: "Miracle Berry",
    value: "Miracle Berry",
  },
  {
    key: "Miracle Seed",
    text: "Miracle Seed",
    value: "Miracle Seed",
  },
  {
    key: "Moon Ball",
    text: "Moon Ball",
    value: "Moon Ball",
  },
  {
    key: "Moon Stone",
    text: "Moon Stone",
    value: "Moon Stone",
  },
  {
    key: "Mystery Berry",
    text: "Mystery Berry",
    value: "Mystery Berry",
  },
  {
    key: "Mystic Water",
    text: "Mystic Water",
    value: "Mystic Water",
  },
  {
    key: "Never-Melt Ice",
    text: "Never-Melt Ice",
    value: "Never-Melt Ice",
  },
  {
    key: "Pink Bow",
    text: "Pink Bow",
    value: "Pink Bow",
  },
  {
    key: "Poison Barb",
    text: "Poison Barb",
    value: "Poison Barb",
  },
  {
    key: "Poke Ball",
    text: "Poke Ball",
    value: "Poke Ball",
  },
  {
    key: "Polkadot Bow",
    text: "Polkadot Bow",
    value: "Polkadot Bow",
  },
  {
    key: "PRZ Cure Berry",
    text: "PRZ Cure Berry",
    value: "PRZ Cure Berry",
  },
  {
    key: "PSN Cure Berry",
    text: "PSN Cure Berry",
    value: "PSN Cure Berry",
  },
  {
    key: "Quick Claw",
    text: "Quick Claw",
    value: "Quick Claw",
  },
  {
    key: "Safari Ball",
    text: "Safari Ball",
    value: "Safari Ball",
  },
  {
    key: "Scope Lens",
    text: "Scope Lens",
    value: "Scope Lens",
  },
  {
    key: "Sharp Beak",
    text: "Sharp Beak",
    value: "Sharp Beak",
  },
  {
    key: "Silver Powder",
    text: "Silver Powder",
    value: "Silver Powder",
  },
  {
    key: "Soft Sand",
    text: "Soft Sand",
    value: "Soft Sand",
  },
  {
    key: "Spell Tag",
    text: "Spell Tag",
    value: "Spell Tag",
  },
  {
    key: "Sport Ball",
    text: "Sport Ball",
    value: "Sport Ball",
  },
  {
    key: "Stick",
    text: "Stick",
    value: "Stick",
  },
  {
    key: "Sun Stone",
    text: "Sun Stone",
    value: "Sun Stone",
  },
  {
    key: "Thick Club",
    text: "Thick Club",
    value: "Thick Club",
  },
  {
    key: "Thunder Stone",
    text: "Thunder Stone",
    value: "Thunder Stone",
  },
  {
    key: "Twisted Spoon",
    text: "Twisted Spoon",
    value: "Twisted Spoon",
  },
  {
    key: "Ultra Ball",
    text: "Ultra Ball",
    value: "Ultra Ball",
  },
  {
    key: "Up-Grade",
    text: "Up-Grade",
    value: "Up-Grade",
  },
  {
    key: "Water Stone",
    text: "Water Stone",
    value: "Water Stone",
  },
];

const GSC_ONLY = [
  {
    key: "Berry",
    text: "Berry",
    value: "Berry",
  },
  {
    key: "Berserk Gene",
    text: "Berserk Gene",
    value: "Berserk Gene",
  },
  {
    key: "Bitter Berry",
    text: "Bitter Berry",
    value: "Bitter Berry",
  },
  {
    key: "Burnt Berry",
    text: "Burnt Berry",
    value: "Burnt Berry",
  },
  {
    key: "Ice Berry",
    text: "Ice Berry",
    value: "Ice Berry",
  },
  {
    key: "Mint Berry",
    text: "Mint Berry",
    value: "Mint Berry",
  },
  {
    key: "Miracle Berry",
    text: "Miracle Berry",
    value: "Miracle Berry",
  },
  {
    key: "Mystery Berry",
    text: "Mystery Berry",
    value: "Mystery Berry",
  },
  {
    key: "PRZ Cure Berry",
    text: "PRZ Cure Berry",
    value: "PRZ Cure Berry",
  },
  {
    key: "Gold Berry",
    text: "Gold Berry",
    value: "Gold Berry",
  },
  {
    key: "Pink Bow",
    text: "Pink Bow",
    value: "Pink Bow",
  },
  {
    key: "Polkadot Bow",
    text: "Polkadot Bow",
    value: "Polkadot Bow",
  },
  {
    key: "PSN Cure Berry",
    text: "PSN Cure Berry",
    value: "PSN Cure Berry",
  },
];

const ADV = GSC.filter((i) => !GSC_ONLY.includes(i)).concat([
  "Aguav Berry",
  "Apicot Berry",
  "Aspear Berry",
  "Belue Berry",
  "Bluk Berry",
  "Cheri Berry",
  "Chesto Berry",
  "Choice Band",
  "Claw Fossil",
  "Cornn Berry",
  "Deep Sea Scale",
  "Deep Sea Tooth",
  "Dive Ball",
  "Dome Fossil",
  "Durin Berry",
  "Enigma Berry",
  "Figy Berry",
  "Ganlon Berry",
  "Grepa Berry",
  "Helix Fossil",
  "Hondew Berry",
  "Iapapa Berry",
  "Kelpsy Berry",
  "Lansat Berry",
  "Lax Incense",
  "Leppa Berry",
  "Liechi Berry",
  "Lum Berry",
  "Luxury Ball",
  "Macho Brace",
  "Mago Berry",
  "Magost Berry",
  "Mental Herb",
  "Nanab Berry",
  "Nest Ball",
  "Net Ball",
  "Nomel Berry",
  "Old Amber",
  "Oran Berry",
  "Pamtre Berry",
  "Pecha Berry",
  "Persim Berry",
  "Petaya Berry",
  "Pinap Berry",
  "Pomeg Berry",
  "Premier Ball",
  "Qualot Berry",
  "Rabuta Berry",
  "Rawst Berry",
  "Razz Berry",
  "Repeat Ball",
  "Root Fossil",
  "Salac Berry",
  "Sea Incense",
  "Shell Bell",
  "Silk Scarf",
  "Sitrus Berry",
  "Soul Dew",
  "Spelon Berry",
  "Starf Berry",
  "Tamato Berry",
  "Timer Ball",
  "Watmel Berry",
  "Wepear Berry",
  "White Herb",
  "Wiki Berry",
]);

const DPP = ADV.concat([
  "Adamant Orb",
  "Armor Fossil",
  "Babiri Berry",
  "Big Root",
  "Black Sludge",
  "Charti Berry",
  "Cherish Ball",
  "Chilan Berry",
  "Choice Scarf",
  "Choice Specs",
  "Chople Berry",
  "Coba Berry",
  "Colbur Berry",
  "Custap Berry",
  "Damp Rock",
  "Dawn Stone",
  "Destiny Knot",
  "Draco Plate",
  "Dread Plate",
  "Dubious Disc",
  "Dusk Ball",
  "Dusk Stone",
  "Earth Plate",
  "Electirizer",
  "Expert Belt",
  "Fist Plate",
  "Flame Orb",
  "Flame Plate",
  "Focus Sash",
  "Full Incense",
  "Grip Claw",
  "Griseous Orb",
  "Haban Berry",
  "Heal Ball",
  "Heat Rock",
  "Icicle Plate",
  "Icy Rock",
  "Insect Plate",
  "Iron Ball",
  "Iron Plate",
  "Jaboca Berry",
  "Kasib Berry",
  "Kebia Berry",
  "Lagging Tail",
  "Life Orb",
  "Light Clay",
  "Lustrous Orb",
  "Magmarizer",
  "Meadow Plate",
  "Metronome",
  "Micle Berry",
  "Mind Plate",
  "Muscle Band",
  "Occa Berry",
  "Odd Incense",
  "Oval Stone",
  "Park Ball",
  "Passho Berry",
  "Payapa Berry",
  "Power Anklet",
  "Power Band",
  "Power Belt",
  "Power Bracer",
  "Power Herb",
  "Power Lens",
  "Power Weight",
  "Protector",
  "Quick Ball",
  "Quick Powder",
  "Rare Bone",
  "Razor Claw",
  "Razor Fang",
  "Reaper Cloth",
  "Rindo Berry",
  "Rock Incense",
  "Rose Incense",
  "Rowap Berry",
  "Shed Shell",
  "Shiny Stone",
  "Shuca Berry",
  "Skull Fossil",
  "Sky Plate",
  "Smooth Rock",
  "Splash Plate",
  "Spooky Plate",
  "Sticky Barb",
  "Stone Plate",
  "Tanga Berry",
  "Toxic Orb",
  "Toxic Plate",
  "Wacan Berry",
  "Wave Incense",
  "Wide Lens",
  "Wise Glasses",
  "Yache Berry",
  "Zap Plate",
  "Zoom Lens",
]);

const BW = DPP.concat([
  "Absorb Bulb",
  "Air Balloon",
  "Big Nugget",
  "Binding Band",
  "Bug Gem",
  "Burn Drive",
  "Cell Battery",
  "Chill Drive",
  "Cover Fossil",
  "Dark Gem",
  "Douse Drive",
  "Dragon Gem",
  "Dream Ball",
  "Eject Button",
  "Electric Gem",
  "Eviolite",
  "Fighting Gem",
  "Fire Gem",
  "Float Stone",
  "Flying Gem",
  "Ghost Gem",
  "Grass Gem",
  "Ground Gem",
  "Ice Gem",
  "Normal Gem",
  "Plume Fossil",
  "Poison Gem",
  "Prism Scale",
  "Psychic Gem",
  "Red Card",
  "Ring Target",
  "Rock Gem",
  "Rocky Helmet",
  "Shock Drive",
  "Steel Gem",
  "Water Gem",
]);

const BERRIES: { [berry: string]: { t: I.TypeName; p: number } } = {
  "Aguav Berry": { t: "Dragon", p: 80 },
  "Apicot Berry": { t: "Ground", p: 100 },
  "Aspear Berry": { t: "Ice", p: 80 },
  "Babiri Berry": { t: "Steel", p: 80 },
  "Belue Berry": { t: "Electric", p: 100 },
  Berry: { t: "Poison", p: 80 },
  "Bitter Berry": { t: "Ground", p: 80 },
  "Bluk Berry": { t: "Fire", p: 90 },
  "Burnt Berry": { t: "Ice", p: 80 },
  "Charti Berry": { t: "Rock", p: 80 },
  "Cheri Berry": { t: "Fire", p: 80 },
  "Chesto Berry": { t: "Water", p: 80 },
  "Chilan Berry": { t: "Normal", p: 80 },
  "Chople Berry": { t: "Fighting", p: 80 },
  "Coba Berry": { t: "Flying", p: 80 },
  "Colbur Berry": { t: "Dark", p: 80 },
  "Cornn Berry": { t: "Bug", p: 90 },
  "Custap Berry": { t: "Ghost", p: 100 },
  "Durin Berry": { t: "Water", p: 100 },
  "Enigma Berry": { t: "Bug", p: 100 },
  "Figy Berry": { t: "Bug", p: 80 },
  "Ganlon Berry": { t: "Ice", p: 100 },
  "Gold Berry": { t: "Psychic", p: 80 },
  "Grepa Berry": { t: "Flying", p: 90 },
  "Haban Berry": { t: "Dragon", p: 80 },
  "Hondew Berry": { t: "Ground", p: 90 },
  "Iapapa Berry": { t: "Dark", p: 80 },
  "Ice Berry": { t: "Grass", p: 80 },
  "Jaboca Berry": { t: "Dragon", p: 100 },
  "Kasib Berry": { t: "Ghost", p: 80 },
  "Kebia Berry": { t: "Poison", p: 80 },
  "Kee Berry": { t: "Fairy", p: 100 },
  "Kelpsy Berry": { t: "Fighting", p: 90 },
  "Lansat Berry": { t: "Flying", p: 100 },
  "Leppa Berry": { t: "Fighting", p: 80 },
  "Liechi Berry": { t: "Grass", p: 100 },
  "Lum Berry": { t: "Flying", p: 80 },
  "Mago Berry": { t: "Ghost", p: 80 },
  "Magost Berry": { t: "Rock", p: 90 },
  "Maranga Berry": { t: "Dark", p: 100 },
  "Micle Berry": { t: "Rock", p: 100 },
  "Mint Berry": { t: "Water", p: 80 },
  "Miracle Berry": { t: "Flying", p: 80 },
  "Mystery Berry": { t: "Fighting", p: 80 },
  "Nanab Berry": { t: "Water", p: 90 },
  "Nomel Berry": { t: "Dragon", p: 90 },
  "Occa Berry": { t: "Fire", p: 80 },
  "Oran Berry": { t: "Poison", p: 80 },
  "Pamtre Berry": { t: "Steel", p: 90 },
  "Passho Berry": { t: "Water", p: 80 },
  "Payapa Berry": { t: "Psychic", p: 80 },
  "Pecha Berry": { t: "Electric", p: 80 },
  "Persim Berry": { t: "Ground", p: 80 },
  "Petaya Berry": { t: "Poison", p: 100 },
  "Pinap Berry": { t: "Grass", p: 90 },
  "Pomeg Berry": { t: "Ice", p: 90 },
  "PRZ Cure Berry": { t: "Fire", p: 80 },
  "PSN Cure Berry": { t: "Electric", p: 80 },
  "Qualot Berry": { t: "Poison", p: 90 },
  "Rabuta Berry": { t: "Ghost", p: 90 },
  "Rawst Berry": { t: "Grass", p: 80 },
  "Razz Berry": { t: "Steel", p: 80 },
  "Rindo Berry": { t: "Grass", p: 80 },
  "Roseli Berry": { t: "Fairy", p: 80 },
  "Rowap Berry": { t: "Dark", p: 100 },
  "Salac Berry": { t: "Fighting", p: 100 },
  "Shuca Berry": { t: "Ground", p: 80 },
  "Sitrus Berry": { t: "Psychic", p: 80 },
  "Spelon Berry": { t: "Dark", p: 90 },
  "Starf Berry": { t: "Psychic", p: 100 },
  "Tamato Berry": { t: "Psychic", p: 90 },
  "Tanga Berry": { t: "Bug", p: 80 },
  "Wacan Berry": { t: "Electric", p: 80 },
  "Watmel Berry": { t: "Fire", p: 100 },
  "Wepear Berry": { t: "Electric", p: 90 },
  "Wiki Berry": { t: "Rock", p: 80 },
  "Yache Berry": { t: "Ice", p: 80 },
};

export const ITEMS = [RBY, GSC, ADV, DPP, BW];

export const ITEMS2 = [
  {
    key: "Berry Juice",
    text: "Berry Juice",
    value: "Berry Juice",
  },
  {
    key: "Black Belt",
    text: "Black Belt",
    value: "Black Belt",
  },
  {
    key: "Black Glasses",
    text: "Black Glasses",
    value: "Black Glasses",
  },
  {
    key: "Bright Powder",
    text: "Bright Powder",
    value: "Bright Powder",
  },
  {
    key: "Charcoal",
    text: "Charcoal",
    value: "Charcoal",
  },
  {
    key: "Dragon Fang",
    text: "Dragon Fang",
    value: "Dragon Fang",
  },
  {
    key: "Dragon Scale",
    text: "Dragon Scale",
    value: "Dragon Scale",
  },
  {
    key: "Fast Ball",
    text: "Fast Ball",
    value: "Fast Ball",
  },
  {
    key: "Fire Stone",
    text: "Fire Stone",
    value: "Fire Stone",
  },
  {
    key: "Focus Band",
    text: "Focus Band",
    value: "Focus Band",
  },
  {
    key: "Friend Ball",
    text: "Friend Ball",
    value: "Friend Ball",
  },
  {
    key: "Great Ball",
    text: "Great Ball",
    value: "Great Ball",
  },
  {
    key: "Hard Stone",
    text: "Hard Stone",
    value: "Hard Stone",
  },
  {
    key: "Heavy Ball",
    text: "Heavy Ball",
    value: "Heavy Ball",
  },
  {
    key: "King's Rock",
    text: "King's Rock",
    value: "King's Rock",
  },
  {
    key: "Leaf Stone",
    text: "Leaf Stone",
    value: "Leaf Stone",
  },
  {
    key: "Leftovers",
    text: "Leftovers",
    value: "Leftovers",
  },
  {
    key: "Level Ball",
    text: "Level Ball",
    value: "Level Ball",
  },
  {
    key: "Light Ball",
    text: "Light Ball",
    value: "Light Ball",
  },
  {
    key: "Love Ball",
    text: "Love Ball",
    value: "Love Ball",
  },
  {
    key: "Lucky Punch",
    text: "Lucky Punch",
    value: "Lucky Punch",
  },
  {
    key: "Lure Ball",
    text: "Lure Ball",
    value: "Lure Ball",
  },
  {
    key: "Magnet",
    text: "Magnet",
    value: "Magnet",
  },
  {
    key: "Mail",
    text: "Mail",
    value: "Mail",
  },
  {
    key: "Master Ball",
    text: "Master Ball",
    value: "Master Ball",
  },
  {
    key: "Metal Coat",
    text: "Metal Coat",
    value: "Metal Coat",
  },
  {
    key: "Metal Powder",
    text: "Metal Powder",
    value: "Metal Powder",
  },
  {
    key: "Miracle Seed",
    text: "Miracle Seed",
    value: "Miracle Seed",
  },
  {
    key: "Moon Ball",
    text: "Moon Ball",
    value: "Moon Ball",
  },
  {
    key: "Moon Stone",
    text: "Moon Stone",
    value: "Moon Stone",
  },
  {
    key: "Mystic Water",
    text: "Mystic Water",
    value: "Mystic Water",
  },
  {
    key: "Never-Melt Ice",
    text: "Never-Melt Ice",
    value: "Never-Melt Ice",
  },
  {
    key: "Poison Barb",
    text: "Poison Barb",
    value: "Poison Barb",
  },
  {
    key: "Poke Ball",
    text: "Poke Ball",
    value: "Poke Ball",
  },
  {
    key: "Quick Claw",
    text: "Quick Claw",
    value: "Quick Claw",
  },
  {
    key: "Safari Ball",
    text: "Safari Ball",
    value: "Safari Ball",
  },
  {
    key: "Scope Lens",
    text: "Scope Lens",
    value: "Scope Lens",
  },
  {
    key: "Sharp Beak",
    text: "Sharp Beak",
    value: "Sharp Beak",
  },
  {
    key: "Silver Powder",
    text: "Silver Powder",
    value: "Silver Powder",
  },
  {
    key: "Soft Sand",
    text: "Soft Sand",
    value: "Soft Sand",
  },
  {
    key: "Spell Tag",
    text: "Spell Tag",
    value: "Spell Tag",
  },
  {
    key: "Sport Ball",
    text: "Sport Ball",
    value: "Sport Ball",
  },
  {
    key: "Stick",
    text: "Stick",
    value: "Stick",
  },
  {
    key: "Sun Stone",
    text: "Sun Stone",
    value: "Sun Stone",
  },
  {
    key: "Thick Club",
    text: "Thick Club",
    value: "Thick Club",
  },
  {
    key: "Thunder Stone",
    text: "Thunder Stone",
    value: "Thunder Stone",
  },
  {
    key: "Twisted Spoon",
    text: "Twisted Spoon",
    value: "Twisted Spoon",
  },
  {
    key: "Ultra Ball",
    text: "Ultra Ball",
    value: "Ultra Ball",
  },
  {
    key: "Up-Grade",
    text: "Up-Grade",
    value: "Up-Grade",
  },
  {
    key: "Water Stone",
    text: "Water Stone",
    value: "Water Stone",
  },
  {
    key: "Aguav Berry",
    text: "Aguav Berry",
    value: "Aguav Berry",
  },
  {
    key: "Apicot Berry",
    text: "Apicot Berry",
    value: "Apicot Berry",
  },
  {
    key: "Aspear Berry",
    text: "Aspear Berry",
    value: "Aspear Berry",
  },
  {
    key: "Belue Berry",
    text: "Belue Berry",
    value: "Belue Berry",
  },
  {
    key: "Bluk Berry",
    text: "Bluk Berry",
    value: "Bluk Berry",
  },
  {
    key: "Cheri Berry",
    text: "Cheri Berry",
    value: "Cheri Berry",
  },
  {
    key: "Chesto Berry",
    text: "Chesto Berry",
    value: "Chesto Berry",
  },
  {
    key: "Choice Band",
    text: "Choice Band",
    value: "Choice Band",
  },
  {
    key: "Claw Fossil",
    text: "Claw Fossil",
    value: "Claw Fossil",
  },
  {
    key: "Cornn Berry",
    text: "Cornn Berry",
    value: "Cornn Berry",
  },
  {
    key: "Deep Sea Scale",
    text: "Deep Sea Scale",
    value: "Deep Sea Scale",
  },
  {
    key: "Deep Sea Tooth",
    text: "Deep Sea Tooth",
    value: "Deep Sea Tooth",
  },
  {
    key: "Dive Ball",
    text: "Dive Ball",
    value: "Dive Ball",
  },
  {
    key: "Dome Fossil",
    text: "Dome Fossil",
    value: "Dome Fossil",
  },
  {
    key: "Durin Berry",
    text: "Durin Berry",
    value: "Durin Berry",
  },
  {
    key: "Enigma Berry",
    text: "Enigma Berry",
    value: "Enigma Berry",
  },
  {
    key: "Figy Berry",
    text: "Figy Berry",
    value: "Figy Berry",
  },
  {
    key: "Ganlon Berry",
    text: "Ganlon Berry",
    value: "Ganlon Berry",
  },
  {
    key: "Grepa Berry",
    text: "Grepa Berry",
    value: "Grepa Berry",
  },
  {
    key: "Helix Fossil",
    text: "Helix Fossil",
    value: "Helix Fossil",
  },
  {
    key: "Hondew Berry",
    text: "Hondew Berry",
    value: "Hondew Berry",
  },
  {
    key: "Iapapa Berry",
    text: "Iapapa Berry",
    value: "Iapapa Berry",
  },
  {
    key: "Kelpsy Berry",
    text: "Kelpsy Berry",
    value: "Kelpsy Berry",
  },
  {
    key: "Lansat Berry",
    text: "Lansat Berry",
    value: "Lansat Berry",
  },
  {
    key: "Lax Incense",
    text: "Lax Incense",
    value: "Lax Incense",
  },
  {
    key: "Leppa Berry",
    text: "Leppa Berry",
    value: "Leppa Berry",
  },
  {
    key: "Liechi Berry",
    text: "Liechi Berry",
    value: "Liechi Berry",
  },
  {
    key: "Lum Berry",
    text: "Lum Berry",
    value: "Lum Berry",
  },
  {
    key: "Luxury Ball",
    text: "Luxury Ball",
    value: "Luxury Ball",
  },
  {
    key: "Macho Brace",
    text: "Macho Brace",
    value: "Macho Brace",
  },
  {
    key: "Mago Berry",
    text: "Mago Berry",
    value: "Mago Berry",
  },
  {
    key: "Magost Berry",
    text: "Magost Berry",
    value: "Magost Berry",
  },
  {
    key: "Mental Herb",
    text: "Mental Herb",
    value: "Mental Herb",
  },
  {
    key: "Nanab Berry",
    text: "Nanab Berry",
    value: "Nanab Berry",
  },
  {
    key: "Nest Ball",
    text: "Nest Ball",
    value: "Nest Ball",
  },
  {
    key: "Net Ball",
    text: "Net Ball",
    value: "Net Ball",
  },
  {
    key: "Nomel Berry",
    text: "Nomel Berry",
    value: "Nomel Berry",
  },
  {
    key: "Oran Berry",
    text: "Oran Berry",
    value: "Oran Berry",
  },
  {
    key: "Pamtre Berry",
    text: "Pamtre Berry",
    value: "Pamtre Berry",
  },
  {
    key: "Pecha Berry",
    text: "Pecha Berry",
    value: "Pecha Berry",
  },
  {
    key: "Persim Berry",
    text: "Persim Berry",
    value: "Persim Berry",
  },
  {
    key: "Petaya Berry",
    text: "Petaya Berry",
    value: "Petaya Berry",
  },
  {
    key: "Pinap Berry",
    text: "Pinap Berry",
    value: "Pinap Berry",
  },
  {
    key: "Pomeg Berry",
    text: "Pomeg Berry",
    value: "Pomeg Berry",
  },
  {
    key: "Premier Ball",
    text: "Premier Ball",
    value: "Premier Ball",
  },
  {
    key: "Qualot Berry",
    text: "Qualot Berry",
    value: "Qualot Berry",
  },
  {
    key: "Rabuta Berry",
    text: "Rabuta Berry",
    value: "Rabuta Berry",
  },
  {
    key: "Rawst Berry",
    text: "Rawst Berry",
    value: "Rawst Berry",
  },
  {
    key: "Razz Berry",
    text: "Razz Berry",
    value: "Razz Berry",
  },
  {
    key: "Repeat Ball",
    text: "Repeat Ball",
    value: "Repeat Ball",
  },
  {
    key: "Root Fossil",
    text: "Root Fossil",
    value: "Root Fossil",
  },
  {
    key: "Salac Berry",
    text: "Salac Berry",
    value: "Salac Berry",
  },
  {
    key: "Sea Incense",
    text: "Sea Incense",
    value: "Sea Incense",
  },
  {
    key: "Shell Bell",
    text: "Shell Bell",
    value: "Shell Bell",
  },
  {
    key: "Silk Scarf",
    text: "Silk Scarf",
    value: "Silk Scarf",
  },
  {
    key: "Sitrus Berry",
    text: "Sitrus Berry",
    value: "Sitrus Berry",
  },
  {
    key: "Soul Dew",
    text: "Soul Dew",
    value: "Soul Dew",
  },
  {
    key: "Spelon Berry",
    text: "Spelon Berry",
    value: "Spelon Berry",
  },
  {
    key: "Starf Berry",
    text: "Starf Berry",
    value: "Starf Berry",
  },
  {
    key: "Tamato Berry",
    text: "Tamato Berry",
    value: "Tamato Berry",
  },
  {
    key: "Timer Ball",
    text: "Timer Ball",
    value: "Timer Ball",
  },
  {
    key: "Watmel Berry",
    text: "Watmel Berry",
    value: "Watmel Berry",
  },
  {
    key: "Wepear Berry",
    text: "Wepear Berry",
    value: "Wepear Berry",
  },
  {
    key: "White Herb",
    text: "White Herb",
    value: "White Herb",
  },
  {
    key: "Wiki Berry",
    text: "Wiki Berry",
    value: "Wiki Berry",
  },
  {
    key: "Adamant Orb",
    text: "Adamant Orb",
    value: "Adamant Orb",
  },
  {
    key: "Armor Fossil",
    text: "Armor Fossil",
    value: "Armor Fossil",
  },
  {
    key: "Babiri Berry",
    text: "Babiri Berry",
    value: "Babiri Berry",
  },
  {
    key: "Big Root",
    text: "Big Root",
    value: "Big Root",
  },
  {
    key: "Black Sludge",
    text: "Black Sludge",
    value: "Black Sludge",
  },
  {
    key: "Charti Berry",
    text: "Charti Berry",
    value: "Charti Berry",
  },
  {
    key: "Cherish Ball",
    text: "Cherish Ball",
    value: "Cherish Ball",
  },
  {
    key: "Chilan Berry",
    text: "Chilan Berry",
    value: "Chilan Berry",
  },
  {
    key: "Choice Scarf",
    text: "Choice Scarf",
    value: "Choice Scarf",
  },
  {
    key: "Choice Specs",
    text: "Choice Specs",
    value: "Choice Specs",
  },
  {
    key: "Chople Berry",
    text: "Chople Berry",
    value: "Chople Berry",
  },
  {
    key: "Coba Berry",
    text: "Coba Berry",
    value: "Coba Berry",
  },
  {
    key: "Colbur Berry",
    text: "Colbur Berry",
    value: "Colbur Berry",
  },
  {
    key: "Custap Berry",
    text: "Custap Berry",
    value: "Custap Berry",
  },
  {
    key: "Damp Rock",
    text: "Damp Rock",
    value: "Damp Rock",
  },
  {
    key: "Dawn Stone",
    text: "Dawn Stone",
    value: "Dawn Stone",
  },
  {
    key: "Destiny Knot",
    text: "Destiny Knot",
    value: "Destiny Knot",
  },
  {
    key: "Draco Plate",
    text: "Draco Plate",
    value: "Draco Plate",
  },
  {
    key: "Dread Plate",
    text: "Dread Plate",
    value: "Dread Plate",
  },
  {
    key: "Dubious Disc",
    text: "Dubious Disc",
    value: "Dubious Disc",
  },
  {
    key: "Dusk Ball",
    text: "Dusk Ball",
    value: "Dusk Ball",
  },
  {
    key: "Dusk Stone",
    text: "Dusk Stone",
    value: "Dusk Stone",
  },
  {
    key: "Earth Plate",
    text: "Earth Plate",
    value: "Earth Plate",
  },
  {
    key: "Electirizer",
    text: "Electirizer",
    value: "Electirizer",
  },
  {
    key: "Expert Belt",
    text: "Expert Belt",
    value: "Expert Belt",
  },
  {
    key: "Fist Plate",
    text: "Fist Plate",
    value: "Fist Plate",
  },
  {
    key: "Flame Orb",
    text: "Flame Orb",
    value: "Flame Orb",
  },
  {
    key: "Flame Plate",
    text: "Flame Plate",
    value: "Flame Plate",
  },
  {
    key: "Focus Sash",
    text: "Focus Sash",
    value: "Focus Sash",
  },
  {
    key: "Full Incense",
    text: "Full Incense",
    value: "Full Incense",
  },
  {
    key: "Grip Claw",
    text: "Grip Claw",
    value: "Grip Claw",
  },
  {
    key: "Griseous Orb",
    text: "Griseous Orb",
    value: "Griseous Orb",
  },
  {
    key: "Haban Berry",
    text: "Haban Berry",
    value: "Haban Berry",
  },
  {
    key: "Heal Ball",
    text: "Heal Ball",
    value: "Heal Ball",
  },
  {
    key: "Heat Rock",
    text: "Heat Rock",
    value: "Heat Rock",
  },
  {
    key: "Icicle Plate",
    text: "Icicle Plate",
    value: "Icicle Plate",
  },
  {
    key: "Icy Rock",
    text: "Icy Rock",
    value: "Icy Rock",
  },
  {
    key: "Insect Plate",
    text: "Insect Plate",
    value: "Insect Plate",
  },
  {
    key: "Iron Ball",
    text: "Iron Ball",
    value: "Iron Ball",
  },
  {
    key: "Iron Plate",
    text: "Iron Plate",
    value: "Iron Plate",
  },
  {
    key: "Jaboca Berry",
    text: "Jaboca Berry",
    value: "Jaboca Berry",
  },
  {
    key: "Kebia Berry",
    text: "Kebia Berry",
    value: "Kebia Berry",
  },
  {
    key: "Lagging Tail",
    text: "Lagging Tail",
    value: "Lagging Tail",
  },
  {
    key: "Life Orb",
    text: "Life Orb",
    value: "Life Orb",
  },
  {
    key: "Light Clay",
    text: "Light Clay",
    value: "Light Clay",
  },
  {
    key: "Lustrous Orb",
    text: "Lustrous Orb",
    value: "Lustrous Orb",
  },
  {
    key: "Magmarizer",
    text: "Magmarizer",
    value: "Magmarizer",
  },
  {
    key: "Meadow Plate",
    text: "Meadow Plate",
    value: "Meadow Plate",
  },
  {
    key: "Metronome",
    text: "Metronome",
    value: "Metronome",
  },
  {
    key: "Micle Berry",
    text: "Micle Berry",
    value: "Micle Berry",
  },
  {
    key: "Mind Plate",
    text: "Mind Plate",
    value: "Mind Plate",
  },
  {
    key: "Muscle Band",
    text: "Muscle Band",
    value: "Muscle Band",
  },
  {
    key: "Occa Berry",
    text: "Occa Berry",
    value: "Occa Berry",
  },
  {
    key: "Odd Incense",
    text: "Odd Incense",
    value: "Odd Incense",
  },
  {
    key: "Oval Stone",
    text: "Oval Stone",
    value: "Oval Stone",
  },
  {
    key: "Park Ball",
    text: "Park Ball",
    value: "Park Ball",
  },
  {
    key: "Passho Berry",
    text: "Passho Berry",
    value: "Passho Berry",
  },
  {
    key: "Payapa Berry",
    text: "Payapa Berry",
    value: "Payapa Berry",
  },
  {
    key: "Power Anklet",
    text: "Power Anklet",
    value: "Power Anklet",
  },
  {
    key: "Power Band",
    text: "Power Band",
    value: "Power Band",
  },
  {
    key: "Power Belt",
    text: "Power Belt",
    value: "Power Belt",
  },
  {
    key: "Power Bracer",
    text: "Power Bracer",
    value: "Power Bracer",
  },
  {
    key: "Power Herb",
    text: "Power Herb",
    value: "Power Herb",
  },
  {
    key: "Power Lens",
    text: "Power Lens",
    value: "Power Lens",
  },
  {
    key: "Power Weight",
    text: "Power Weight",
    value: "Power Weight",
  },
  {
    key: "Protector",
    text: "Protector",
    value: "Protector",
  },
  {
    key: "Quick Ball",
    text: "Quick Ball",
    value: "Quick Ball",
  },
  {
    key: "Quick Powder",
    text: "Quick Powder",
    value: "Quick Powder",
  },
  {
    key: "Rare Bone",
    text: "Rare Bone",
    value: "Rare Bone",
  },
  {
    key: "Razor Claw",
    text: "Razor Claw",
    value: "Razor Claw",
  },
  {
    key: "Razor Fang",
    text: "Razor Fang",
    value: "Razor Fang",
  },
  {
    key: "Reaper Cloth",
    text: "Reaper Cloth",
    value: "Reaper Cloth",
  },
  {
    key: "Rindo Berry",
    text: "Rindo Berry",
    value: "Rindo Berry",
  },
  {
    key: "Rock Incense",
    text: "Rock Incense",
    value: "Rock Incense",
  },
  {
    key: "Rose Incense",
    text: "Rose Incense",
    value: "Rose Incense",
  },
  {
    key: "Rowap Berry",
    text: "Rowap Berry",
    value: "Rowap Berry",
  },
  {
    key: "Shed Shell",
    text: "Shed Shell",
    value: "Shed Shell",
  },
  {
    key: "Shiny Stone",
    text: "Shiny Stone",
    value: "Shiny Stone",
  },
  {
    key: "Shuca Berry",
    text: "Shuca Berry",
    value: "Shuca Berry",
  },
  {
    key: "Skull Fossil",
    text: "Skull Fossil",
    value: "Skull Fossil",
  },
  {
    key: "Sky Plate",
    text: "Sky Plate",
    value: "Sky Plate",
  },
  {
    key: "Smooth Rock",
    text: "Smooth Rock",
    value: "Smooth Rock",
  },
  {
    key: "Splash Plate",
    text: "Splash Plate",
    value: "Splash Plate",
  },
  {
    key: "Spooky Plate",
    text: "Spooky Plate",
    value: "Spooky Plate",
  },
  {
    key: "Sticky Barb",
    text: "Sticky Barb",
    value: "Sticky Barb",
  },
  {
    key: "Stone Plate",
    text: "Stone Plate",
    value: "Stone Plate",
  },
  {
    key: "Tanga Berry",
    text: "Tanga Berry",
    value: "Tanga Berry",
  },
  {
    key: "Toxic Orb",
    text: "Toxic Orb",
    value: "Toxic Orb",
  },
  {
    key: "Toxic Plate",
    text: "Toxic Plate",
    value: "Toxic Plate",
  },
  {
    key: "Wacan Berry",
    text: "Wacan Berry",
    value: "Wacan Berry",
  },
  {
    key: "Wave Incense",
    text: "Wave Incense",
    value: "Wave Incense",
  },
  {
    key: "Wide Lens",
    text: "Wide Lens",
    value: "Wide Lens",
  },
  {
    key: "Wise Glasses",
    text: "Wise Glasses",
    value: "Wise Glasses",
  },
  {
    key: "Yache Berry",
    text: "Yache Berry",
    value: "Yache Berry",
  },
  {
    key: "Zap Plate",
    text: "Zap Plate",
    value: "Zap Plate",
  },
  {
    key: "Zoom Lens",
    text: "Zoom Lens",
    value: "Zoom Lens",
  },
  {
    key: "Absorb Bulb",
    text: "Absorb Bulb",
    value: "Absorb Bulb",
  },
  {
    key: "Air Balloon",
    text: "Air Balloon",
    value: "Air Balloon",
  },
  {
    key: "Big Nugget",
    text: "Big Nugget",
    value: "Big Nugget",
  },
  {
    key: "Binding Band",
    text: "Binding Band",
    value: "Binding Band",
  },
  {
    key: "Burn Drive",
    text: "Burn Drive",
    value: "Burn Drive",
  },
  {
    key: "Cell Battery",
    text: "Cell Battery",
    value: "Cell Battery",
  },
  {
    key: "Chill Drive",
    text: "Chill Drive",
    value: "Chill Drive",
  },
  {
    key: "Cover Fossil",
    text: "Cover Fossil",
    value: "Cover Fossil",
  },
  {
    key: "Dark Gem",
    text: "Dark Gem",
    value: "Dark Gem",
  },
  {
    key: "Douse Drive",
    text: "Douse Drive",
    value: "Douse Drive",
  },
  {
    key: "Dream Ball",
    text: "Dream Ball",
    value: "Dream Ball",
  },
  {
    key: "Eject Button",
    text: "Eject Button",
    value: "Eject Button",
  },
  {
    key: "Float Stone",
    text: "Float Stone",
    value: "Float Stone",
  },
  {
    key: "Plume Fossil",
    text: "Plume Fossil",
    value: "Plume Fossil",
  },
  {
    key: "Red Card",
    text: "Red Card",
    value: "Red Card",
  },
  {
    key: "Ring Target",
    text: "Ring Target",
    value: "Ring Target",
  },
  {
    key: "Rock Gem",
    text: "Rock Gem",
    value: "Rock Gem",
  },
  {
    key: "Rocky Helmet",
    text: "Rocky Helmet",
    value: "Rocky Helmet",
  },
  {
    key: "Shock Drive",
    text: "Shock Drive",
    value: "Shock Drive",
  },
  {
    key: "Steel Gem",
    text: "Steel Gem",
    value: "Steel Gem",
  },
  {
    key: "Water Gem",
    text: "Water Gem",
    value: "Water Gem",
  },
  {
    key: "Blue Orb",
    text: "Blue Orb",
    value: "Blue Orb",
  },
  {
    key: "Kee Berry",
    text: "Kee Berry",
    value: "Kee Berry",
  },
  {
    key: "Luminous Moss",
    text: "Luminous Moss",
    value: "Luminous Moss",
  },
  {
    key: "Maranga Berry",
    text: "Maranga Berry",
    value: "Maranga Berry",
  },
  {
    key: "Pixie Plate",
    text: "Pixie Plate",
    value: "Pixie Plate",
  },
  {
    key: "Red Orb",
    text: "Red Orb",
    value: "Red Orb",
  },
  {
    key: "Roseli Berry",
    text: "Roseli Berry",
    value: "Roseli Berry",
  },
  {
    key: "Sablenite",
    text: "Sablenite",
    value: "Sablenite",
  },
  {
    key: "Sachet",
    text: "Sachet",
    value: "Sachet",
  },
  {
    key: "Safety Goggles",
    text: "Safety Goggles",
    value: "Safety Goggles",
  },
  {
    key: "Sail Fossil",
    text: "Sail Fossil",
    value: "Sail Fossil",
  },
  {
    key: "Snowball",
    text: "Snowball",
    value: "Snowball",
  },
  {
    key: "Weakness Policy",
    text: "Weakness Policy",
    value: "Weakness Policy",
  },
  {
    key: "Whipped Dream",
    text: "Whipped Dream",
    value: "Whipped Dream",
  },
  {
    key: "Adrenaline Orb",
    text: "Adrenaline Orb",
    value: "Adrenaline Orb",
  },
  {
    key: "Beast Ball",
    text: "Beast Ball",
    value: "Beast Ball",
  },
  {
    key: "Bottle Cap",
    text: "Bottle Cap",
    value: "Bottle Cap",
  },
  {
    key: "Bug Memory",
    text: "Bug Memory",
    value: "Bug Memory",
  },
  {
    key: "Dark Memory",
    text: "Dark Memory",
    value: "Dark Memory",
  },
  {
    key: "Dragon Memory",
    text: "Dragon Memory",
    value: "Dragon Memory",
  },
  {
    key: "Electric Memory",
    text: "Electric Memory",
    value: "Electric Memory",
  },
  {
    key: "Electric Seed",
    text: "Electric Seed",
    value: "Electric Seed",
  },
  {
    key: "Ice Stone",
    text: "Ice Stone",
    value: "Ice Stone",
  },
  {
    key: "Misty Seed",
    text: "Misty Seed",
    value: "Misty Seed",
  },
  {
    key: "Poison Memory",
    text: "Poison Memory",
    value: "Poison Memory",
  },
  {
    key: "Protective Pads",
    text: "Protective Pads",
    value: "Protective Pads",
  },
  {
    key: "Psychic Memory",
    text: "Psychic Memory",
    value: "Psychic Memory",
  },
  {
    key: "Psychic Seed",
    text: "Psychic Seed",
    value: "Psychic Seed",
  },
  {
    key: "Psychium Z",
    text: "Psychium Z",
    value: "Psychium Z",
  },
  {
    key: "Rock Memory",
    text: "Rock Memory",
    value: "Rock Memory",
  },
  {
    key: "Water Memory",
    text: "Water Memory",
    value: "Water Memory",
  },
  {
    key: "Berry Sweet",
    text: "Berry Sweet",
    value: "Berry Sweet",
  },
  {
    key: "Blunder Policy",
    text: "Blunder Policy",
    value: "Blunder Policy",
  },
  {
    key: "Chipped Pot",
    text: "Chipped Pot",
    value: "Chipped Pot",
  },
  {
    key: "Cracked Pot",
    text: "Cracked Pot",
    value: "Cracked Pot",
  },
  {
    key: "Eject Pack",
    text: "Eject Pack",
    value: "Eject Pack",
  },
  {
    key: "Flower Sweet",
    text: "Flower Sweet",
    value: "Flower Sweet",
  },
  {
    key: "Galarica Cuff",
    text: "Galarica Cuff",
    value: "Galarica Cuff",
  },
  {
    key: "Galarica Wreath",
    text: "Galarica Wreath",
    value: "Galarica Wreath",
  },
  {
    key: "Heavy-Duty Boots",
    text: "Heavy-Duty Boots",
    value: "Heavy-Duty Boots",
  },
  {
    key: "Leek",
    text: "Leek",
    value: "Leek",
  },
  {
    key: "Berry",
    text: "Berry",
    value: "Berry",
  },
  {
    key: "Berserk Gene",
    text: "Berserk Gene",
    value: "Berserk Gene",
  },
  {
    key: "Bitter Berry",
    text: "Bitter Berry",
    value: "Bitter Berry",
  },
  {
    key: "Burnt Berry",
    text: "Burnt Berry",
    value: "Burnt Berry",
  },
  {
    key: "Ice Berry",
    text: "Ice Berry",
    value: "Ice Berry",
  },
  {
    key: "Mint Berry",
    text: "Mint Berry",
    value: "Mint Berry",
  },
  {
    key: "Miracle Berry",
    text: "Miracle Berry",
    value: "Miracle Berry",
  },
  {
    key: "Mystery Berry",
    text: "Mystery Berry",
    value: "Mystery Berry",
  },
  {
    key: "PRZ Cure Berry",
    text: "PRZ Cure Berry",
    value: "PRZ Cure Berry",
  },
  {
    key: "Gold Berry",
    text: "Gold Berry",
    value: "Gold Berry",
  },
  {
    key: "Pink Bow",
    text: "Pink Bow",
    value: "Pink Bow",
  },
  {
    key: "Polkadot Bow",
    text: "Polkadot Bow",
    value: "Polkadot Bow",
  },
  {
    key: "PSN Cure Berry",
    text: "PSN Cure Berry",
    value: "PSN Cure Berry",
  },
  {
    key: "Old Amber",
    text: "Old Amber",
    value: "Old Amber",
  },
  {
    key: "Amulet Coin",
    text: "Amulet Coin",
    value: "Amulet Coin",
  },
  {
    key: "Soothe Bell",
    text: "Soothe Bell",
    value: "Soothe Bell",
  },
  {
    key: "Exp. Share",
    text: "Exp. Share",
    value: "Exp. Share",
  },
];
